### ISSUE TITLE
Setup ES-Lint and Prettier

### ISSUE THREAD

**Issue by sarthakkundra** [moja-global/contributor-website-v2#2]
To follow standard coding conventions all along the project, let's setup a pre-commit hook using ES-Lint and Prettier. 

Refer [article](https://medium.com/dubizzletechblog/setting-up-prettier-and-eslint-for-js-and-react-apps-bbc779d29062) for any guidance.

**Comment by sarthakkundra** [comment]
Sure. Go ahead. Make sure to work on the `init` branch.

**Comment by Abhishek-kumar09** [comment]
@sarthakkundra  I thought you are asking to create a PR against `init` branch, but there is no such branch.
